# Assignment 4
author: Dominika Maciąg

In [183]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import string
from sklearn.linear_model import LogisticRegression

def remove_punctuation(text):
    import string
    translator = str.maketrans('', '', string.punctuation)
    return text.translate(translator)

baby_df = pd.read_csv('amazon_baby.csv')
baby_df.head()

name  \
0                           Planetwise Flannel Wipes   
1                              Planetwise Wipe Pouch   
2                Annas Dream Full Quilt with 2 Shams   
3  Stop Pacifier Sucking without tears with Thumb...   
4  Stop Pacifier Sucking without tears with Thumb...   

                                              review  rating  
0  These flannel wipes are OK, but in my opinion ...       3  
1  it came early and was not disappointed. i love...       5  
2  Very soft and comfortable and warmer than it l...       5  
3  This is a product well worth the purchase.  I ...       5  
4  All of my kids have cried non-stop when I trie...       5

## Exercise 1 (data preparation)
a) Remove punctuation from reviews using the given function.   
b) Replace all missing (nan) revies with empty "" string.  
c) Drop all the entries with rating = 3, as they have neutral sentiment.   
d) Set all positive ($\geq$4) ratings to 1 and negative($\leq$2) to -1.

In [184]:
# b) Replace all missing (nan) revies with empty "" string.
# To aply given function we need firstly to remove all the NaN from "review" row in our dataframe.

print("before replacement: ", baby_df["review"][38])
baby_df["review"].replace(np.nan, "", inplace=True)
print("after replacement: ", baby_df["review"][38])

#short test:
baby_df["review"][38] == baby_df["review"][38]

before replacement:  nan
after replacement:  


True

In [185]:
#a) Remove punctuation from reviews using the given function.
baby_df["review"] = baby_df["review"].apply(remove_punctuation)

# short test: 
baby_df["review"][4] == 'All of my kids have cried nonstop when I tried to ween them off their pacifier until I found Thumbuddy To Loves Binky Fairy Puppet  It is an easy way to work with your kids to allow them to understand where their pacifier is going and help them part from itThis is a must buy book and a great gift for expecting parents  You will save them soo many headachesThanks for this book  You all rock'
remove_punctuation(baby_df["review"][4]) == 'All of my kids have cried nonstop when I tried to ween them off their pacifier until I found Thumbuddy To Loves Binky Fairy Puppet  It is an easy way to work with your kids to allow them to understand where their pacifier is going and help them part from itThis is a must buy book and a great gift for expecting parents  You will save them soo many headachesThanks for this book  You all rock'

True

In [186]:
#c) Drop all the entries with rating = 3, as they have neutral sentiment.
rows = len(baby_df.index)

for i in range(0,rows):
    if(baby_df["rating"][i]==3):
        baby_df.drop(i, inplace=True)
#         print(baby_df["rating"][i])
    
#short test:
sum(baby_df["rating"] == 3)

0

In [187]:
baby_df.head(20)

name  \
1                               Planetwise Wipe Pouch   
2                 Annas Dream Full Quilt with 2 Shams   
3   Stop Pacifier Sucking without tears with Thumb...   
4   Stop Pacifier Sucking without tears with Thumb...   
5   Stop Pacifier Sucking without tears with Thumb...   
6             A Tale of Baby's Days with Peter Rabbit   
7   Baby Tracker&reg; - Daily Childcare Journal, S...   
8   Baby Tracker&reg; - Daily Childcare Journal, S...   
9   Baby Tracker&reg; - Daily Childcare Journal, S...   
10  Baby Tracker&reg; - Daily Childcare Journal, S...   
11  Baby Tracker&reg; - Daily Childcare Journal, S...   
12  Baby Tracker&reg; - Daily Childcare Journal, S...   
14     Nature's Lullabies First Year Sticker Calendar   
15     Nature's Lullabies First Year Sticker Calendar   
16     Nature's Lullabies First Year Sticker Calendar   
17    Nature's Lullabies Second Year Sticker Calendar   
18    Nature's Lullabies Second Year Sticker Calendar   
19    Nature's Lullabies Second Year Sticker Calendar   
20    Nature's Lullabies Second Year Sticker Calendar   
21    Nature's Lullabies Second Year Sticker Calendar   

                                               review  rating  
1   it came early and was not disappointed i love ...       5  
2   Very soft and comfortable and warmer than it l...       5  
3   This is a product well worth the purchase  I h...       5  
4   All of my kids have cried nonstop when I tried...       5  
5   When the Binky Fairy came to our house we didn...       5  
6   Lovely book its bound tightly so you may not b...       4  
7   Perfect for new parents We were able to keep t...       5  
8   A friend of mine pinned this product on Pinter...       5  
9   This has been an easy way for my nanny to reco...       4  
10  I love this journal and our nanny uses it ever...       4  
11  This book is perfect  Im a first time new mom ...       5  
12  I originally just gave the nanny a pad of pape...       4  
14  Space for monthly photos info and a lot of use...       5  
15  I bought this calender for myself for my secon...       4  
16  I love this little calender you can keep track...       5  
17  This was the only calender I could find for th...       5  
18  I completed a calendar for my sons first year ...       4  
19  We wanted to get something to keep track of ou...       5  
20  I had a hard time finding a second year calend...       5  
21  I only purchased a secondyear calendar for my ...       2

In [188]:
# d)  Set all positive ( ≥ 4) ratings to 1 and negative( ≤ 2) to -1.
baby_df["rating"].replace(1, -1, inplace = True)
baby_df["rating"].replace(2, -1, inplace = True)
baby_df["rating"].replace(4, 1, inplace = True)
baby_df["rating"].replace(5, 1, inplace = True)
#short test:
sum(baby_df["rating"]**2 != 1)

0

In [189]:
baby_df.head(20)

name  \
1                               Planetwise Wipe Pouch   
2                 Annas Dream Full Quilt with 2 Shams   
3   Stop Pacifier Sucking without tears with Thumb...   
4   Stop Pacifier Sucking without tears with Thumb...   
5   Stop Pacifier Sucking without tears with Thumb...   
6             A Tale of Baby's Days with Peter Rabbit   
7   Baby Tracker&reg; - Daily Childcare Journal, S...   
8   Baby Tracker&reg; - Daily Childcare Journal, S...   
9   Baby Tracker&reg; - Daily Childcare Journal, S...   
10  Baby Tracker&reg; - Daily Childcare Journal, S...   
11  Baby Tracker&reg; - Daily Childcare Journal, S...   
12  Baby Tracker&reg; - Daily Childcare Journal, S...   
14     Nature's Lullabies First Year Sticker Calendar   
15     Nature's Lullabies First Year Sticker Calendar   
16     Nature's Lullabies First Year Sticker Calendar   
17    Nature's Lullabies Second Year Sticker Calendar   
18    Nature's Lullabies Second Year Sticker Calendar   
19    Nature's Lullabies Second Year Sticker Calendar   
20    Nature's Lullabies Second Year Sticker Calendar   
21    Nature's Lullabies Second Year Sticker Calendar   

                                               review  rating  
1   it came early and was not disappointed i love ...       1  
2   Very soft and comfortable and warmer than it l...       1  
3   This is a product well worth the purchase  I h...       1  
4   All of my kids have cried nonstop when I tried...       1  
5   When the Binky Fairy came to our house we didn...       1  
6   Lovely book its bound tightly so you may not b...       1  
7   Perfect for new parents We were able to keep t...       1  
8   A friend of mine pinned this product on Pinter...       1  
9   This has been an easy way for my nanny to reco...       1  
10  I love this journal and our nanny uses it ever...       1  
11  This book is perfect  Im a first time new mom ...       1  
12  I originally just gave the nanny a pad of pape...       1  
14  Space for monthly photos info and a lot of use...       1  
15  I bought this calender for myself for my secon...       1  
16  I love this little calender you can keep track...       1  
17  This was the only calender I could find for th...       1  
18  I completed a calendar for my sons first year ...       1  
19  We wanted to get something to keep track of ou...       1  
20  I had a hard time finding a second year calend...       1  
21  I only purchased a secondyear calendar for my ...      -1

## Summary: 
As we can see in c) after we removed all the rows where rating was equal to 3 the test that checks sum of all rows where rating was equal to 3 returned 0 as expected. All rows with rating equal to 3 where successfully deleted.

In d) we use replace function just as in b) but this time we replace values lesser than 3 with -1 and values greater than 3 with 1.

## Exercise 2 
a) Split dataset into training and test sets.     
b) Transform reviews into vectors using CountVectorizer. 

In [190]:
# a)
from sklearn.model_selection import train_test_split

train, test = train_test_split(baby_df, train_size=0.8, test_size=0.2)

In [191]:
# print("train:", list(train["review"])[3])
# print("test:", list(test["review"])[3])

# b)
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
x_train = vectorizer.fit_transform(list(train["review"]))
x_test = vectorizer.transform(list(test["review"]))


## Summary:
We cleaned our data: we delated rows that are neutral and labeled all positive reviews as 1 and negative as -1. After that we separated our dataset into training and test sets. With all that preparations we can train logistic regression so that it learns which words have positive and negative meaning.

## Exercise 3 
a) Train LogisticRegression model on training data (reviews processed with CountVectorizer, ratings as they were).   
b) Print 10 most positive and 10 most negative words.

In [192]:
#a)
y_train = train["rating"]
# print(list(y_train))

model = LogisticRegression(solver='lbfgs', max_iter=20000)
model.fit(x_train, y_train)

LogisticRegression(max_iter=20000)

In [193]:
#b)
# Get the indices of the sorted cofficients
ascending = np.argsort(model.coef_.flatten()) 
descending = ascending[::-1]

vocab = np.array(vectorizer.get_feature_names_out())

# Print most positive words
print("Most positive words: ", end="")
for i in range(10):
    print(vocab[descending[i]], end=", ")
print("\n")

# Print most negative words
print("Most negative words: ", end="")
for i in range(10):
    print(vocab[ascending[i]], end=", ")
print("\n")

#hint: model.coef_, vectorizer.get_feature_names()

Most positive words: lifesaver, saves, amazed, downside, rich, pleasantly, skeptical, excellent, perfect, awesome, 

Most negative words: disappointing, worthless, dissapointed, worst, poorly, theory, useless, unusable, concept, poor, 



## Summary:
In this exercise we are interpreting the coefficients of a logistic regression fit on the products rating. \
descending[0] contains the index of the largest coefficient \
vocab[descending[0]] contains the word corresponding to the largest coefficient

As we can see some results are not perfect since even some positive reviews can describe some drawbacks that product can have.

## Exercise 4 
a) Predict the sentiment of test data reviews.   
b) Predict the sentiment of test data reviews in terms of probability.   
c) Find five most positive and most negative reviews.   
d) Calculate the accuracy of predictions.

In [194]:
# a)
model.predict(x_test)

array([ 1, -1,  1, ...,  1,  1,  1], dtype=int64)

In [195]:
# b)
pred = model.predict_proba(x_test)
print(pred)
#hint: model.predict_proba()

[[5.54762287e-06 9.99994452e-01]
 [6.06921903e-01 3.93078097e-01]
 [1.40350976e-03 9.98596490e-01]
 ...
 [1.65920156e-01 8.34079844e-01]
 [2.29161997e-04 9.99770838e-01]
 [1.72776667e-02 9.82722333e-01]]


In [196]:
# c) Find five most positive and most negative reviews.
ascendingproba = np.argsort(pred[:,[0]].flatten()) 

#     Positive reviews
print("Five most positive reviews: ")
for i in range (5):
    print(i+1, ")")
    print(list(train["review"])[ascendingproba[i]])

print()
print()
print("Five most negative reviews: ")
#     Negative reviews
descendingproba = ascendingproba[::-1]
for i in range (5):
    print(i+1, ")")
    print(list(train["review"])[descendingproba[i]])

Five most positive reviews: 
1 )
This is the second of this type of product Ive purchased  They are both well made with no loose stitching and all elastic working properly  In practice these diapers work well as intended
2 )
Tubing could be a little bit longer but otherwise it works great for my medela pump in style breast pump
3 )
We have an older dog 26 lbs and need to confine her to different parts of the house over the course of the day  Each of the three openings is a different widthThe smallest is 32 inches and this opening requires the extensions on the end to be screwed out to the point where you worry they will hold without breaking but we have caught clothing on the edges multple times and no breaks to dateThe second widest is 36 inches and with one short extension piece inserted this one was a really tight fit  The good news is that once you get it in place there is little risk of breaking because the gate is plenty strong enough even for a big dogThe widest opening is 48 in

In [197]:
# d) Calculate the accuracy of predictions.
y_test = test["rating"]
model.score(x_test, y_test)

0.9317861533387305

## Summary:
We find five most positive and negative reviews and calculate the accuracy of our prediction. Accuracy is very high - it is 93% right.

## Exercise 5
In this exercise we will limit the dictionary of CountVectorizer to the set of significant words, defined below.


a) Redo exercises 2-5 using limited dictionary.   
b) Check the impact of all the words from the dictionary.   
c) Compare accuracy of predictions and the time of evaluation.

In [198]:
# 5a)
words = ["ply", "saves", "minor", "rich", "skeptical", "excellent", "downside", "pleasantly", "worry", "thankful","dissapointed", "disappointing", "worthless", "worst", "poorly", "concept", "theory", "poor", "intelligent", "useless"]

# Excercise 2
# Transform reviews into vectors using CountVectorizer. We limiting dictionary of CountVectorizer
vectorizer_dict = CountVectorizer(vocabulary=words)
x_train_dict = vectorizer_dict.fit_transform(list(train["review"]))
x_test_dict = vectorizer_dict.transform(list(test["review"]))

# Excercise 3
# Train LogisticRegression model on training data
y_train_dict = train["rating"]
model_dict = LogisticRegression(solver='lbfgs', max_iter=20000)
model_dict.fit(x_train_dict, y_train_dict)

LogisticRegression(max_iter=20000)

In [200]:
# Print 10 most positive and 10 most negative words

# Get the indices of the sorted cofficients
ascending_d = np.argsort(model_dict.coef_.flatten()) 
descending_d = ascending_d[::-1]

vocab_dict = np.array(vectorizer_dict.get_feature_names_out())

# Print most positive words
print("Most positive words: ", end="")
for i in range(10):
    print(vocab_dict[descending_d[i]], end=", ")
print("\n")

# Print most negative words
print("Most negative words: ", end="")
for i in range(10):
    print(vocab_dict[ascending_d[i]], end=", ")
print("\n")

Most positive words: pleasantly, saves, skeptical, downside, excellent, worry, rich, minor, thankful, ply, 

Most negative words: theory, worst, disappointing, poorly, worthless, dissapointed, poor, useless, intelligent, concept, 



In [201]:
# Excercise 4
#  Predict the sentiment of test data reviews
model_dict.predict(x_test_dict)

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [202]:
# Predict the sentiment of test data reviews in terms of probability
pred_d = model_dict.predict_proba(x_test_dict)
print(pred_d)

[[0.1482568 0.8517432]
 [0.1482568 0.8517432]
 [0.1482568 0.8517432]
 ...
 [0.1482568 0.8517432]
 [0.1482568 0.8517432]
 [0.1482568 0.8517432]]


In [203]:
# Find five most positive and most negative reviews.
ascendingproba_d = np.argsort(pred_d[:,[0]].flatten()) 

print("Five most positive reviews: ")
for i in range (5):
    print(i+1, ") ")
    print(list(train["review"])[ascendingproba_d[i]])

print()
print("Five most negative reviews: ")
descendingproba_d = ascendingproba_d[::-1]
for i in range (5):
    print(i+1, ")")
    print(list(train["review"])[descendingproba_d[i]])

Five most positive reviews: 
1 ) 
We just got a two pack of these and I think we have finally found the winner for our newborns bottles  Our challenge has been to find a bottle that has a very low flow rate combined with a natural feel so that our baby boy will still latch naturally to the breast  These do the trick  The 5 oz model has a low flow rate and the model is simple to clean  So far it is worth every penny
2 ) 
My daughter loves the quality of this swing  Its great that it rocks in two separate planes and there are a number of ways to configure the music the volume the visuals etc  Love it
3 ) 
Usually with these 34organic34 sheets and mattress pads they are much stiffer than the others  This one was surprisingly soft  both the sheet and the topper  As others have noted it is manufactured in China  sometimes that can be of concern  but it seems to be good quality  Not sure if its truly 100 organic but so few things actually are
4 ) 
Didnt use it for more than a week but when s

In [204]:
# Calculate the accuracy of predictions.
y_test_dict = test["rating"]
model_dict.score(x_test_dict, y_test_dict)

0.8533177415969536

## Summary:
We once again want to train logistic regression to recognize negative and positive words but this time we are using additional dictionary. Since our dictionary is limited in size I expected predictions to have smaller accuracy. Those assumptions where correct because the accuracy dropped by 8.6%.

In [205]:
# b) Check the impact of all the words from the dictionary.
# print (model_dict.coef_)
for i in range (len(words)):
    print(words[i], end=": ")
    print(model_dict.coef_.flatten()[i])

ply: 0.2133573145182058
saves: 1.9675248424235015
minor: 1.0030858261343543
rich: 1.203121839440074
skeptical: 1.6454419476966997
excellent: 1.3797073916000562
downside: 1.572422554413102
pleasantly: 2.0353207079266036
worry: 1.2269214896322693
thankful: 0.6272665445856024
dissapointed: -2.3437074585799373
disappointing: -2.8174570030334114
worthless: -2.4879953387713245
worst: -2.8663648765377823
poorly: -2.781189381303166
concept: -1.5733252904495842
theory: -2.992956963642512
poor: -2.3034883646108644
intelligent: -2.080154684797976
useless: -2.2761743628709787


In [206]:
#c) Compare accuracy of predictions and the time of evaluation.
import sys, time

# Oryginal accuracy: 0.9302569638091811
# After using dictionary: 0.8516686156337141

#hint: %time, %timeit

In [227]:
%timeit model_dict.score(x_test_dict, y_test_dict)

3.85 ms ± 678 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [226]:
%time model_dict.score(x_test_dict, y_test_dict)

CPU times: total: 0 ns
Wall time: 5.99 ms


0.8533177415969536

In [228]:
%timeit model.score(x_test, y_test)

16 ms ± 447 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [223]:
%time model.score(x_test, y_test)

CPU times: total: 31.2 ms
Wall time: 21.9 ms


0.9317861533387305

## Summary:
As we can see original predictions were more precise but we pay this precision in time complexity of the cell evaluation.